### PR TITLE
Fix issue with hanging thread

### PR DESCRIPTION
**Pull request by aria42**

### CODE REVIEW

**Comment by aria42** [comment]
Waiting for green-light from shippable

**Comment by dcdowney** [comment]
Am I understanding correctly that the current code is failing on "shippable" right now?

And shippable is some aggregate build that AI2 does, and we should wait for that to succeed before we merge back to the main branch?

If so (a) next time I won't merge like I did a couple hours ago before shippable passes, and (b) I don't understand why shippable is failing because the tests all pass in my environment.  The logs above are saying there was one bad thread in ConllCRFEndToEndTest but that test passes for me.

**Comment by aria42** [comment]
You can ignore for now, there seems to be a bug in shippable. It's only running `gradle test`, but for some reason the thread tests fail there. I imagine it's because of running inside a container or some other test-environment reason. I'll probably remove the assertion for now.

**Comment by dcdowney** [comment]
To follow-through: this is ready to merge from my perspective.

**Comment by aria42** [comment]
I can merge, there's a bug with Shippable (a service that runs tests on each PR) I'm trying to figure out. but I'll merge and worry later

**Pull request merged**
